### ISSUE TITLE
Needs more stolen lannonbr css

### ISSUE THREAD

**Issue by Joshua-Gordon** [jrddunbr/mp451sp2019#1]

**Comment by jrddunbr** [comment]
*sigh*

**Comment by jrddunbr** [comment]
***HOLD THE PHONE***
![css](https://user-images.githubusercontent.com/14130505/54159182-c5d29580-4422-11e9-8231-e7956e51a56d.png)

**Comment by jrddunbr** [comment]
Seriously, it looks like only Ryan, Reece, and I have custom CSS. Hunter2 at least has Ben's CSS. Is that even CSS? What level of CSS are you on right now? :D

**Comment by Joshua-Gordon** [comment]
That's the temporary page for Jeanna to look at. I'm up to my ass in CSS on my own system. Here's a sneak preview:
![alternative text](https://i.imgur.com/s2GyHyQ.png)
The picture does not do the animations justice. Also note the button to automatically steal Ben's CSS.
That is what level of CSS I am on right now.

**Comment by jrddunbr** [comment]
Ah yes. Presumably css **shake** and <marque>tags</marque>

**Comment by jrddunbr** [comment]
Wait *a* ***MINUTE***.

# **WHO TOLD YOU THAT YOU COULD USE HORIZONTAL RULES**

/s

**Comment by jrddunbr** [comment]
*sjdljsdfl* ** jdsfjsldfdslskf**

# HEADEEEERRRR
